const { ethers } = require("hardhat");

/**
 * Deploy ZKIdentity + ReputationOracle
 * Then register the Age and Unique verifiers.
 *
 * Run: npx hardhat run scripts/deploy.js --network polygon_mumbai
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("\n🚀 ZK-Identity Deployment");
  console.log("═══════════════════════════════════════");
  console.log("Deployer:", deployer.address);
  console.log(
    "Balance:",
    ethers.formatEther(await ethers.provider.getBalance(deployer.address)),
    "ETH\n"
  );

  // ── 1. Deploy ZKIdentity ─────────────────────────────────────────────────
  const ZKIdentity = await ethers.getContractFactory("ZKIdentity");
  const zkIdentity = await ZKIdentity.deploy();
  await zkIdentity.waitForDeployment();
  console.log("✅ ZKIdentity deployed to:      ", await zkIdentity.getAddress());

  // ── 2. Deploy ReputationOracle ───────────────────────────────────────────
  const ReputationOracle = await ethers.getContractFactory("ReputationOracle");
  const oracle = await ReputationOracle.deploy();
  await oracle.waitForDeployment();
  console.log("✅ ReputationOracle deployed to:", await oracle.getAddress());

  // ── 3. Deploy Groth16 Verifiers (generated by snarkjs) ──────────────────
  // IMPORTANT: Generate these from your compiled circuits first:
  //   snarkjs zkey export solidityverifier age.zkey AgeVerifierGroth16.sol
  //   snarkjs zkey export solidityverifier unique.zkey UniqueVerifierGroth16.sol

  let ageVerifierAddress = "0x0000000000000000000000000000000000000000";
  let uniqueVerifierAddress = "0x0000000000000000000000000000000000000000";

  try {
    const AgeVerifier = await ethers.getContractFactory("AgeVerifierGroth16");
    const ageVerifier = await AgeVerifier.deploy();
    await ageVerifier.waitForDeployment();
    ageVerifierAddress = await ageVerifier.getAddress();
    console.log("✅ AgeVerifier deployed to:     ", ageVerifierAddress);
  } catch {
    console.log("⚠️  AgeVerifierGroth16 not compiled yet.");
    console.log("   Run: circom circuits/AgeVerifier.circom && snarkjs groth16 setup ...");
  }

  try {
    const UniqueVerifier = await ethers.getContractFactory("UniqueHumanGroth16");
    const uniqueVerifier = await UniqueVerifier.deploy();
    await uniqueVerifier.waitForDeployment();
    uniqueVerifierAddress = await uniqueVerifier.getAddress();
    console.log("✅ UniqueVerifier deployed to:  ", uniqueVerifierAddress);
  } catch {
    console.log("⚠️  UniqueHumanGroth16 not compiled yet.");
  }

  // ── 4. Register verifiers in ZKIdentity ──────────────────────────────────
  if (ageVerifierAddress !== "0x0000000000000000000000000000000000000000") {
    await zkIdentity.registerVerifier(1, ageVerifierAddress);
    console.log("✅ Age verifier registered for claimType=1");
  }

  if (uniqueVerifierAddress !== "0x0000000000000000000000000000000000000000") {
    await zkIdentity.registerVerifier(2, uniqueVerifierAddress);
    console.log("✅ Unique verifier registered for claimType=2");
  }

  // ── 5. Authorize deployer as oracle (for testing) ────────────────────────
  await oracle.setOracleStatus(deployer.address, true);
  console.log("✅ Deployer authorized as ReputationOracle signer");

  // ── 6. Save addresses ─────────────────────────────────────────────────────
  const fs = require("fs");
  const deployedAddresses = {
    zkIdentity:        await zkIdentity.getAddress(),
    reputationOracle:  await oracle.getAddress(),
    ageVerifier:       ageVerifierAddress,
    uniqueVerifier:    uniqueVerifierAddress,
    network:           (await ethers.provider.getNetwork()).name,
    deployedAt:        new Date().toISOString(),
  };

  fs.writeFileSync(
    "./deployments.json",
    JSON.stringify(deployedAddresses, null, 2)
  );

  console.log("\n═══════════════════════════════════════");
  console.log("📄 Addresses saved to deployments.json");
  console.log("🔗 Verify on Etherscan:");
  console.log(
    `   npx hardhat verify --network polygon_mumbai ${await zkIdentity.getAddress()}`
  );
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
  });
